AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/**/*"
    - "bin/**/*"

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
